/* Generated by :claw at 2022-03-22T18:10:10.825538Z */

#include <stddef.h>
#if defined(__cplusplus)
#include <new>
#endif



#include "assimp/cimport.h"
#include "assimp/cfileio.h"
#include "assimp/scene.h"
#include "assimp/postprocess.h"


#if !defined(__CLAW_API)
#  if defined(_WIN32)
#    define __CLAW_API __declspec(dllexport)
#  elif defined(__GNUC__)
#    define __CLAW_API __attribute__((visibility("default")))
#  else
#    define __CLAW_API
#  endif
#endif

#ifdef _WIN32
#  include <windows.h>
static HMODULE ___claw_module;

static int ___claw_init_wrapper() {
  ___claw_module = GetModuleHandle(NULL);
  return ___claw_module != NULL;
}

static void ___claw_close_wrapper(void) {
}
#else
#  include <dlfcn.h>
static void* ___claw_module;

static int ___claw_init_wrapper() {
  ___claw_module = dlopen(NULL, RTLD_NOW | RTLD_GLOBAL);
  return ___claw_module != NULL;
}

static void ___claw_close_wrapper(void) {
}
#endif

static void* claw_get_proc_addr(const char *name) {
  if(___claw_module == NULL) {
    return NULL;
  }

#ifdef _WIN32
  return (void*) GetProcAddress(___claw_module, name);
#else
  return dlsym(___claw_module, name);
#endif
}

#if defined(__cplusplus)
extern "C" {
#endif

typedef struct aiLogStream (*aiGetPredefinedLogStream_t)(enum aiDefaultLogStream,const char*);
typedef aiReturn (*aiGetMaterialInteger_t)(const struct aiMaterial*,const char*,unsigned int,unsigned int,int*);
typedef aiReturn (*aiGetMaterialFloat_t)(const struct aiMaterial*,const char*,unsigned int,unsigned int,ai_real*);

static aiGetPredefinedLogStream_t __v_claw_aiGetPredefinedLogStream;
static aiGetMaterialInteger_t __v_claw_aiGetMaterialInteger;
static aiGetMaterialFloat_t __v_claw_aiGetMaterialFloat;

__CLAW_API int __claw_aw_assimp_loader_5DA53F6A98A30162A8623B6E17B80A948CCD1B41() {
  if(___claw_init_wrapper()) {

__v_claw_aiGetPredefinedLogStream = (aiGetPredefinedLogStream_t) claw_get_proc_addr("aiGetPredefinedLogStream");
__v_claw_aiGetMaterialInteger = (aiGetMaterialInteger_t) claw_get_proc_addr("aiGetMaterialInteger");
__v_claw_aiGetMaterialFloat = (aiGetMaterialFloat_t) claw_get_proc_addr("aiGetMaterialFloat");

    ___claw_close_wrapper();
    return 0;
  }
  return 1;
}


__CLAW_API struct aiLogStream* __claw_aiGetPredefinedLogStream(struct aiLogStream* __claw_result_, enum aiDefaultLogStream pStreams, const char* file) {
// /home/borodust/devel/repo/aw-projects/aw-assimp/src/lib/assimp/include/assimp/cimport.h:280:33
(*__claw_result_) = aiGetPredefinedLogStream(pStreams, file);
return __claw_result_;
}

__CLAW_API aiReturn __claw_aiGetMaterialInteger(const struct aiMaterial* pMat, const char* pKey, unsigned int type, unsigned int index, int* pOut) {
// /home/borodust/devel/repo/aw-projects/aw-assimp/src/lib/assimp/include/assimp/material.h:1562:17
return aiGetMaterialInteger(pMat, pKey, type, index, pOut);
}

__CLAW_API aiReturn __claw_aiGetMaterialFloat(const struct aiMaterial* pMat, const char* pKey, unsigned int type, unsigned int index, ai_real* pOut) {
// /home/borodust/devel/repo/aw-projects/aw-assimp/src/lib/assimp/include/assimp/material.h:1537:17
return aiGetMaterialFloat(pMat, pKey, type, index, pOut);
}

#if defined(__cplusplus)
}
#endif
