/* Generated by :claw at 2021-11-04T11:38:24.806447Z */

#include <stddef.h>
#if defined(__cplusplus)
#include <new>
#endif



#include "assimp/cimport.h"
#include "assimp/cfileio.h"
#include "assimp/scene.h"
#include "assimp/postprocess.h"


#if !defined(__CLAW_API)
#  if defined(_WIN32)
#    define __CLAW_API __declspec(dllexport)
#  elif defined(__GNUC__)
#    define __CLAW_API __attribute__((visibility("default")))
#  else
#    define __CLAW_API
#  endif
#endif

#ifdef _WIN32
#  include <windows.h>
static HMODULE ___claw_module;

static int ___claw_init_wrapper() {
  ___claw_module = GetModuleHandle(NULL);
  return ___claw_module != NULL;
}

static void ___claw_close_wrapper(void) {
}
#else
#  include <dlfcn.h>
static void* ___claw_module;

static int ___claw_init_wrapper() {
  ___claw_module = dlopen(NULL, RTLD_NOW | RTLD_GLOBAL);
  return ___claw_module != NULL;
}

static void ___claw_close_wrapper(void) {
}
#endif

static void* claw_get_proc_addr(const char *name) {
  if(___claw_module == NULL) {
    return NULL;
  }

#ifdef _WIN32
  return (void*) GetProcAddress(___claw_module, name);
#else
  return dlsym(___claw_module, name);
#endif
}

#if defined(__cplusplus)
extern "C" {
#endif

typedef struct aiLogStream (*aiGetPredefinedLogStream_t)(enum aiDefaultLogStream,const char*);

static aiGetPredefinedLogStream_t __v_claw_aiGetPredefinedLogStream;

__CLAW_API int __claw_aw_assimp_loader_5DA53F6A98A30162A8623B6E17B80A948CCD1B41() {
  if(___claw_init_wrapper()) {

__v_claw_aiGetPredefinedLogStream = (aiGetPredefinedLogStream_t) claw_get_proc_addr("aiGetPredefinedLogStream");

    ___claw_close_wrapper();
    return 0;
  }
  return 1;
}


__CLAW_API struct aiLogStream* __claw_aiGetPredefinedLogStream(struct aiLogStream* __claw_result_, enum aiDefaultLogStream pStreams, const char* file) {
// /home/borodust/devel/repo/aw-projects/aw-assimp/src/lib/assimp/include/assimp/cimport.h:277:33
(*__claw_result_) = aiGetPredefinedLogStream(pStreams, file);
return __claw_result_;
}

#if defined(__cplusplus)
}
#endif
